### ISSUE TITLE
JSON serde with Enum support for data model

### ISSUE THREAD

**Issue by jpy-luke** [menu-hanke/forest-data-model#30]
Currently the Enum typed variables like ReferenceTree.species (type TreeSpecies) get serialized with their value only for JSON. This does not seem to trivially deserialize as the TreeSpecies type. Investigate for a solution. This problem does not appear in Pickle serde.

Suggested potential fix:
* Create a serialization/deserialization functionality which is able to serialize and deserialize the Enum type members of ForestStand, ReferenceTree and TreeStratum correctly. Take this into use in vmi-data-converter for serialization and sim-workbench for deserialization.

**Comment by unie31** [comment]
closed by 
https://github.com/menu-hanke/sim-workbench/pull/115 and 
https://github.com/menu-hanke/vmi-data-converter/pull/189
