### ISSUE TITLE
Use type annotations from typing module

### ISSUE THREAD

**Issue by dmela** [menu-hanke/forest-data-model#5]
We try to keep the compatibility down to 3.7 so we need to introduce types from the `typing` module.

In other words type annotations such as `list[...]` and `tuple[...]` should be changed to correspond `List[...]` and `Tuple[...]` where `List` and `Tuple` are imported from `typing` module.

**Comment by jpy-luke** [comment]
I disagree. Let's drop the 3.7 requirement and not carry it on anymore to new code. 3.9 and 3.10 are already the defaults from in Valtori software center and nobody we know is (or should be) using lower anymore.
